### PR TITLE
Fix readRemaining

### PR DESCRIPTION
**Pull request by e5l**

### CODE REVIEW

**Comment by cy6erGn0m** [comment]
Thanks!

**Comment by cy6erGn0m** [comment]
The fix is available in dev build 0.1.5-dev-4

**Comment by jrocharodrigues** [comment]
I had this issue ( Kotlin/kotlinx-io#360 ) when using serialization and ktor. Forced the use of kotlinx-io-0.1.5-dev-4 and org.jetbrains.kotlinx:kotlinx-coroutines-io-0.1.5-dev-4 and confirm this issue is solved. 

However when using Ktor MockEngine to mock the the Json answer i got an error similar to the previous one i reported (the limit is different though) `Invalid JSON at 4088: Unexpected end in string`

Could this error be related to this issue, or should i open a new on for Ktor?

Thanks in advance

**Comment by e5l** [comment]
It looks like the separate issue from kx.io could you file an issue with reproducer or data sample?

**Comment by jrocharodrigues** [comment]
Ok, i have opened an issue in ktor, but i will close it, and open one in kx.io

**Comment by jrocharodrigues** [comment]
Done: https://github.com/Kotlin/kotlinx-io/issues/38

**Pull request merged**
