### PR TITLE
Update kotlin version, enable library mode

### PR DESCRIPTION
**Pull request by e5l**

### CODE REVIEW

**Comment by e5l** [comment]
No problem

**Comment by Sirrah** [comment]
I'd also like to see a `kotlinx-io` release build against Kotlin 1.3.71. Is there anything I can do to help it along?

**Comment by e5l** [comment]
Yep. You can use it from the `ktor-io` module in ktor(`implementation 'io.ktor:ktor-io:1.3.2'` for gradle)

**Comment by Sirrah** [comment]
Thanks for the tip, I'll look into that.

**Comment by e5l** [comment]
closed as obsolete

**Pull request closed without merging**
