### PR TITLE
Trick the webpack to bypass its warnings on missing modules

### PR DESCRIPTION
**Pull request by fzhinkin**
Leftovers from #265

### CODE REVIEW

**Review by whyoleg — APPROVED** [review]
LGTM
But, is there a reason why Wasm and JS implementations are different?
In my experiments current approach works for both Wasm and JS, and so the implementation looks similar (except for minor differences in jsinterop for wasm vs js), so it's easier to understand the code and so could mostly copy-pasted

**Comment by fzhinkin** [comment]
> But, is there a reason why Wasm and JS implementations are different?

There was a reason, but now it seems like it should be possible to unify it.

**Comment by fzhinkin** [comment]
Filed https://github.com/Kotlin/kotlinx-io/issues/287 for unifying module loading

**Comment by lppedd** [comment]
I've missed the discussion about this change. Why couldn't Webpack simply be configured to mute those warnings?

E.g., configure `externals`, or use the ignore plugin.

**Comment by fzhinkin** [comment]
@lppedd If I understand correctly, it could be done on the library user side only, which is kinda lame. Instead, the root cause of the warning was fixed (well, not fixed, but muted).

**Comment by lppedd** [comment]
@fzhinkin Thanks. I get that not displaying a warning consumer side is nice, but isn't it better to make the consumer aware of what is going on instead of hiding it? I mean, once I start working with K/JS I know that Webpack runs for `browser`, so I can fiddle with its configuration in case. This could be highlighted in the readme.

**Pull request merged**
